POST http://localhost:3000/api/auth/login 
Content-Type: application/json

{
    "email": "example@mail.com", 
    "password": "login123456"
}

###

GET http://localhost:3000/api/auth/check-auth
Authorization: Bearer token

###
# by userId
GET http://localhost:3000/api/auth/refresh/56fe9911-b3a4-4ca7-89d8-d275213e23d4
Authorization: Bearer token

