version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq

    ports:
      - ${RABBITMQ_WEB_UI_PORT}:15672
      - ${RABBITMQ_PORT}:5672

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
