version: '3.9'
services:
  mongo.db:
    image: mongo:4.4
    restart: always
    container_name: mongo.db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo.db:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ${MONGO_STORAGE}:/data/db

  mongo.ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: mongo.ui
    depends_on:
      - mongo.db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo.db:${MONGO_PORT}/
